### ISSUE TITLE
e621_noclose wont run on admistrator

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#12]
When it run it on administrator it won't work and this is the error code it get.

C:\WINDOWS\system32>e621dl.exe
'e621dl.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>pause
Press any key to continue . . .

 it runs when i click it normaly same if i rune the program itself on administror but not the no_close command

**Comment by lurkbbs** [comment]
Yeah, that's what I suspected. I answered in another issue, but take a copy anyway
[e621_noclose.zip](https://github.com/lurkbbs/e621dl/files/3934897/e621_noclose.zip)
