### ISSUE TITLE
What is the 404 static1.e621.net error that pops up sometimes

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#13]
I have to leave for work so ill make this quick
I tried to download by DB config but it stops after a bit and doesn't do anyting keeps opened but doesn't close or stop
I can't show you what I see exactly since it wouldn't let me copy it but what was diffrent was
posts so far: 320 
filtered; 87  
everyting else is just None so far

this is my config.
[4 Config Data (DB).txt](https://github.com/lurkbbs/e621dl/files/3935545/4.Config.Data.DB.txt)

my api config works fine but not my db one it just seems to freeze. it looks like its still running but nothing changes. Ill let it run during work to be on the safe side and let you know if anything changes if your not able to get to it by then.
Edit1: just got back from work and nothing changed and it didn't close
Edit2: found the problem it was a traceback error that was caused by misnaming a subfolder in the subfolders section in another subfolder. don't know why it didn't put up an error and close however

**Comment by huskelord** [comment]
So i figured out the above problem but i have a new question. What is up with the static1.e621.net error that pops up in the last warning: line in the program. just curious

Edit1: so i noticed a bug when an error appears it will not close down but will run until i close it myself (this with every way i could think to run it) I have gotten past this by recording the program when it runs but and going back to the video to see what the error code was.

**Comment by lurkbbs** [comment]
> Edit2: found the problem it was a traceback error that was caused by misnaming a subfolder in the subfolders section in another subfolder. don't know why it didn't put up an error and close however

Thanks. It should, and I should change it to print error and exit at least.

> What is up with the static1.e621.net error that pops up in the last warning: line in the program. just curious

That is just debug line that I should probably get rid of. It means some links to images in db no longer exists, probably because they were deleted. I was planning to mark these images as deleted in database later. Well, later is still later. Just ignore them for now

**Comment by lurkbbs** [comment]
New release, at least now the app should exit with informative error if subfolders option is incorrect.

**Comment by huskelord** [comment]
Thank you.

**Comment by lurkbbs** [comment]
You're welcome!
