### ISSUE TITLE
* in initial request causes 403 retry loop

### ISSUE THREAD

**Issue by RedLXIX** [lurkbbs/e621dl#19]
I just created my first config.ini file to test moving over my config.yaml from the Wulfre/e621dl repo clone. However, after converting my blacklist to a single line and performing a test run, it seemed like it was processing, but it didn't look like any progress was being made.

What jumped out at me amongst the thousands of lines of the same thing was it was reporting 'unexpected absense of hidden input'. Doing some digging, I tracked it down to the call to https://e621.net/post/index.json coming back with a 403. And the reason why the console log was getting spammed was because it kept attempting to process the call but obviously never made any progress.....yet the script didn't die, either :/

I spit out the payload and booted it up in postman to get a better idea of what was going on.
limit: '320'
before_id: '2147483647'
tags: 'date:>=2019-12-07 breasts -*_vore -all_the_way_through -amputation -amputee -baby'
The response was 403 Forbidden with this as the result:
{
    "success": false,
    "reason": "access denied",
    "message": "To use wildcards you must have an activated account at least one week old."
}
When I moved the *_vore further into the blacklist, it processed just fine.
I checked the readme and such but couldn't find references to my user credentials or API key, so I wasn't sure if it had login capabilities, but even so I'd think that shouldn't be an issue. I hadn't encountered it with the Wulfre repo :/

So, nothing super critical, but might want to take a look? I did find a workaround, just moving it in the list, but the docs _do_ say "You can use ~, - and * wildcards for every tags, not only first five" and that one did end up in the first 5 just from the sorting I'd done.

Thanks!

**Comment by lurkbbs** [comment]
>.....yet the script didn't die, either :/

Thanks for the bug report! _This_ I should fix relatively quickly.

> What jumped out at me amongst the thousands of lines of the same thing was it was reporting 'unexpected absense of hidden input'

What was the tool where it was reported. It looks useful.

> I checked the readme and such but couldn't find references to my user credentials or API key, so I wasn't sure if it had login capabilities, but even so I'd think that shouldn't be an issue.

Thanks for the enchancement request 😄 
Indeed it doesn't. I plan to rewrite some parts of logic (and to move to YAML), so no new features until next month, but I will add it eventually.

> "To use wildcards you must have an activated account at least one week old."

I just tried it on the site itself. It tells me the same. Looks like they restricted it recently, IDK why.

> I hadn't encountered it with the Wulfre repo :/

That is extremely strange, since it's e621 restriction. Are you sure there is no problem now with Wulfre's fork?

**Comment by lurkbbs** [comment]
Fixed here: https://github.com/lurkbbs/e621dl/releases/tag/v5.8.1
