### ISSUE TITLE
Folder within Folder

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#2]
I figured out a workaround by using the ~ key to get the same results but i was wondering if ther was a way to have a folder with folders inside of it during download for example a Scalie images folder and a Scalie animated folder inside of Scalie forlder. While also having that folder inside a folder called tags next to a folder called artist with a folder for each artist inside it.
basicly

1.  Artist
    - Washa
        - Images
        - Animated
    - etc.
2. Tags
    - Scalie
        - Images
        - Animated
    - etc
Also is there a way to set the days to look infinit day in the past?

**Comment by lurkbbs** [comment]
No, there is no way to make folder inside folder right now, due to a duplicate finding code shortcuts.

But! As I understand this is a needed feature and it's not really that hard to impliment. Gimme day or two, and you'll get it in this form:

```
[Artist/Washa/Images]
tags = ...
...

[Artist/Washa/Animated]
tags = ...
...

[etc/and so on]
tags = ...
...
```

If you want to describe folder structure in another way, feel free to suggest it, but it won't be that fast.

P.S. Just in case, `tags = ~a ~b ~c` will find all posts with these combinations of tags:
```a
b
c
a b
a c
b c
a b c
```
If that's what you want, all is good

EDIT:
No way for infinity, I usually just set it to 300000000. To be fair, it's mostly for backward compatibility with Wulfre's fork, when I wanted for codebase to be mostly similar.
EDIT2:
Also, what was unclear in conditions? Should there be more examples or something? This is a major feature and I want its description to be undestandable for everyone.

**Comment by lurkbbs** [comment]
OK, new commit should work:
https://github.com/lurkbbs/e621dl/archive/master.zip
Use '\\' or '/' as folder separator. If something is not working, please post error message.

**Comment by huskelord** [comment]
Its kind of hard to undersand the wording used in the example and how sertian things work since im not good at programing or reading programing. If you could explain and add a example of exluding posts only if two tags are in the post together but not if one of them is missing. 
For example I was trying to get rid of posts with tags male and solo but then i relized i just had to make sure that the posts had a female intersex or ambigus gender tag with the ~.
Also being bad at programing and all that how do I get the commit to work with program?  In case it matters I downloaded the executable release not the source release or python for that matter.
I tried just downloading from the link you posted above and extracting in the file I had the program in. If that was supposed to be it then it didn't work after running the original program and trying to run the extracted program.

**Comment by lurkbbs** [comment]
First, on solo without male, condition is `condition = -(male & solo)` but yes, `~` is better in this case, load on e621 should be less.
As for why program is not working, I need more info.

1. What is your previous version of a program? Mine or Wulfre's? That is, config looks like this:

```
toggles:
    include_md5: false
default_search:
    days: 1
    min_score: 0
    min_favs: 0
    ratings:
        - s
blacklist:
searches:
    cats:
        tags:
            - cat
            - yellow_fur
    dogs:
        tags:
            - dog
            - brown_fur
```


Or like this:


```
;;;;;;;;;;;;;;
;; GENERAL  ;;
;;;;;;;;;;;;;;

[Defaults]
days = 1
ratings = s
min_score = 0
min_favs = 0
post_source = api

[Blacklist]
tags =

[Settings]
include_md5 = false
make_hardlinks = true
make_cache = true
db = true

[cats]
tags = cat yellow_fur

[dogs]
tags = dog brown_fur
```

2. The link is to the source code version. You need to install latest Python to use this version. Do you install it? Steps are here:
https://github.com/lurkbbs/e621dl#installing-and-setting-up-e621dl

3. If you are having trouble with Python, wait a bit, I'll make an executable version.

**Comment by lurkbbs** [comment]
OK, catch executable version:
https://github.com/lurkbbs/e621dl/releases/download/v5.2.0/e621dl.exe

**Comment by huskelord** [comment]
I downloaded your executabe version and my config file has always looked like the second one however it still works fine. Thank you very much for the help by the way.

**Comment by lurkbbs** [comment]
You're welcome!
