### ISSUE TITLE
new site broke the script

### ISSUE THREAD

**Issue by ponchojohn1234** [lurkbbs/e621dl#20]
the new site layout broke the script
![broke script](https://user-images.githubusercontent.com/59420956/76053296-58bce780-5f32-11ea-8cd6-47be555676f2.PNG)

**Comment by jahkyah** [comment]
I can confirm that this is happening consistently.

![image](https://user-images.githubusercontent.com/53247317/76054678-78a6d800-5f3f-11ea-8f9a-e03cb3338ad2.png)

**Comment by jahkyah** [comment]
I can confirm that this is happening consistently.

 
![image](https://user-images.githubusercontent.com/53247317/76054874-126e8500-5f40-11ea-88a1-84e54c4f9c1e.png)

**Comment by lurkbbs** [comment]
\*tired groan\*
I hope they changed api for a _very_ good reason.
Please, wait three days top, I should adapt new code by then.

**Comment by lurkbbs** [comment]
They do have a good reason, by the way. So, good news, everyone, tag limit is 40 tags, 8 times more than before.
We'll wait if API rate limit is lower than one second.

**Comment by jahkyah** [comment]
> They do have a good reason, by the way. So, good news, everyone, tag limit is 40 tags, 8 times more than before.
> We'll wait if API rate limit is lower than one second.

That is interesting. I wonder what their reasons are for. Wouldn't be too surprised if they want the API rate lower.

**Comment by lurkbbs** [comment]
I said 3 days? Well, I adapted it to a new API a bit earlier. With support for API key authorization as well.

As it turns out, custom internal representation of all posts info makes it not only easier to work with, but also really easy to adapt to new API by just mapping to old one.

When you found new bugs, write me either here or on e621, same username.

**Comment by jahkyah** [comment]
I just created an account on e621 about 10 minutes ago and I am getting Unauthorized for URL error.

When I comment out the login part I am able to run the script just fine. I am not sure if it will work with just the API though.

Do I need to wait a week or two before I can use the login and API section in the settings?

![image](https://user-images.githubusercontent.com/53247317/76135342-21af0a80-5ff4-11ea-9009-1f388b8352b0.png)

**Comment by lurkbbs** [comment]
> I just created an account on e621 about 10 minutes ago and I am getting Unauthorized for URL error.

Not sure. Just to be clear, do you use login and api key (should look like "333f07428b3db3b85b2bc410493a8ec6" ) or do you use password (I shouldn't know how it should look)?

If password, then proceed to [account settings](https://e621.net/users/home), then "Manage API Access", then type password and finally generate API key.

If it's not, make sure settings look like this:

```
[Settings]
; optionally some settings above
login = username
api_key = 333f07428b3db3b85b2bc410493a8ec6
; optionally some settings below
```

Maybe there is some spelling mistake in settings.

If everything still looks fine, try this url in a browser:
`https://e621.net/tags.json?login=username&api_key=333f07428b3db3b85b2bc410493a8ec6`

with replaced `username` and `333f07428b3db3b85b2bc410493a8ec6`. There should be no error. If it is, post it here.

> Do I need to wait a week or two before I can use the login and API section in the settings?

I honestly don't know.

**Comment by jahkyah** [comment]
Funny enough I can actually access the url you posted with my username and API.

screenshot of the tags.json

![image](https://user-images.githubusercontent.com/53247317/76139910-250dba80-6023-11ea-89a4-fa3b96855aa2.png)

This is what my settings look like:

![image](https://user-images.githubusercontent.com/53247317/76139937-64d4a200-6023-11ea-9850-d5c464d0484f.png)

The API key in the screenshot is no longer valid but this is an example.

Just to make sure I understood, I am to use my username for the login?

Do you have a template config that I can use? I am wondering if the config I am using is incompatible with the new version. 

(I used to use an older version like 5.6.4 or something like that lol)

Attached is my config.ini

[config.zip](https://github.com/lurkbbs/e621dl/files/4301571/config.zip)

**Comment by lurkbbs** [comment]
Sadly, "it works on mine machine" 😔 
Just downloaded your config, replaced your credentials with mine and all works.

Yes, your e621 username in `login`, and api key in `api_key`.

Luckily, while I typed this, I've got the bug. My key had no big letters, and my code do calls `lower()` on the value 🤦‍♂ 

try this: [e621dl.zip](https://github.com/lurkbbs/e621dl/files/4302331/e621dl.zip)
