### ISSUE TITLE
IndexError: List index out of range

### ISSUE THREAD

**Issue by jahkyah** [lurkbbs/e621dl#21]
![image](https://user-images.githubusercontent.com/53247317/76146808-ffed6c00-6063-11ea-89c1-2671580f6e2f.png)

When I do a large amount of searches I am getting this error. 

It seems to stall out at the same spot.

I cannot get it running again till I refresh the config.ini file.

IE:

It checks if the tags are valid but when it resumes from the last known download it throws this exception.

I have to over write the config to get it running again otherwise it will throw the exception again.

**Comment by lurkbbs** [comment]
@jahkyah Thanks for the swift bag reports!

The problem appears if all page consisted of hidden posts, they are filtered from internal processing. Should work in the latest release and current master.

https://github.com/lurkbbs/e621dl/releases/tag/v5.9.1

Api key lowercasing also fixed.

**Comment by lurkbbs** [comment]
Disregard that, a new bug appeared

**Comment by jahkyah** [comment]
> Disregard that, a new bug appeared

I created an issue before seeing this reply!

**Comment by lurkbbs** [comment]
Answered before seeing this reply. OK, everything should be fixed now

**Comment by jahkyah** [comment]
Thanks for the bug fixes!
