### ISSUE TITLE
NameError: name 'files' is not defined

### ISSUE THREAD

**Issue by jahkyah** [lurkbbs/e621dl#22]
Hi!

I am getting this error when I try to run the latest version.

![image](https://user-images.githubusercontent.com/53247317/76151410-e871ab80-6082-11ea-8984-b07e6e61788f.png)

I notice we have a files.db file but I am not sure if that is relevant!

Wanted to let you know!

**Comment by lurkbbs** [comment]
You're fast :-D
Yes, fixed in oops commit. I've just updated release.

**Comment by jahkyah** [comment]
Thanks for the bugfix!
