### ISSUE TITLE
Error when trying to download posts

### ISSUE THREAD

**Issue by jahkyah** [lurkbbs/e621dl#23]
Hi!

The script executes and successfully checks tags.

When it attempts to download posts its throws this error:

![image](https://user-images.githubusercontent.com/53247317/76151890-92ebcd80-6087-11ea-8624-b37cb80ce7f1.png)

I was wondering if it was an issue with my login and API so I commented it out. 

This did not fix the issue!

**Comment by lurkbbs** [comment]
I should assume `files.db` was deleted and `download_queue.pickle` and `config_queue.pickle` was not.

Try delete everything that is not folders and `e621dl.py`

**Comment by lurkbbs** [comment]
I assumed wrong

**Comment by jahkyah** [comment]
> I should assume `files.db` was deleted and `download_queue.pickle` and `config_queue.pickle` was not.
> 
> Try delete everything that is not folders and `e621dl.py`

I deleted everything that was not the downloads folder and unfortunately this did not seem to fix the issue. :(

**Comment by lurkbbs** [comment]
OK, first let's try this:
[e621dl.zip](https://github.com/lurkbbs/e621dl/files/4302498/e621dl.zip)

Edit: 99 little bugs in the code, 99 little bugs in the code. Take one down, patch it around 117 little bugs in the code. Never old joke was so true.

**Comment by jahkyah** [comment]
When I run the attached script I am getting this prompt:

![image](https://user-images.githubusercontent.com/53247317/76152547-ac444800-608e-11ea-849d-a1b7ceaec498.png)


Not sure if that is meant to happen?

**Comment by lurkbbs** [comment]
No, it's not. But please, check if it actually downloads something. If it works, latest "aargh commit" should work with normal indication

**Comment by jahkyah** [comment]
Huzzah!

I created a test config and it is pulling posts in!

![image](https://user-images.githubusercontent.com/53247317/76152674-2cb77880-6090-11ea-8e64-948d5fb43cc8.png)

**Comment by lurkbbs** [comment]
![image](https://user-images.githubusercontent.com/38856256/76152701-960cab00-60d3-11ea-82fd-5becb8d22759.png)

Finally. Sorry for this fail train and thanks for reports!

At least it's done faster than three days 😄

**Comment by jahkyah** [comment]
> ![image](https://user-images.githubusercontent.com/38856256/76152701-960cab00-60d3-11ea-82fd-5becb8d22759.png)
> 
> Finally. Sorry for this fail train and thanks for reports!
> 
> At least it's done faster than three days 😄

You are all good! I apologize for the bother!!

I will open a new issue if I come across another one. (Hopefully not) 😜
