### ISSUE TITLE
MissingSectionHeaderError: File contains no section headers

### ISSUE THREAD

**Issue by ponchojohn1234** [lurkbbs/e621dl#24]
im getting this error when trying to download with a login and api key set
it does not happen when tying to download without these values set

![broke script 2](https://user-images.githubusercontent.com/59420956/76155083-d147b380-60ac-11ea-8365-653c8be99180.PNG)

![broke script 3](https://user-images.githubusercontent.com/59420956/76155105-271c5b80-60ad-11ea-8e9e-369647b8e9a6.PNG)

**Comment by lurkbbs** [comment]
Uncomment line

```
;[Settings]
```

as well, e.g.:

```
[Settings]
login = username
api_key = key
```
