### ISSUE TITLE
Files Not Downloading?

### ISSUE THREAD

**Issue by ChillAnon** [lurkbbs/e621dl#27]
So for some reason when I try anything other than a very simple tag, files will not download for me. I always get something that looks like this:

```
status: All complete
checked tag: all tags are valid
current config: config.ini
current section: test folder
recent warning: None so far
recent file downloaded: None so far
connection retries: None so far
posts so far: 245
already exist: None so far
downloaded: None so far
copied: None so far
filtered: 245
not found on e621: None so far
```

It will show posts and filter them, but it won't download them. I've tried waiting for 5-20minute intervals to see if it would download, but to no avail.

I know I installed the program properly because if I use a simple tag with no other parameters it works, so like this:

`[Test Folder]
tags = cat`

But then when I try adding parameters, like this, it doesn't download files for me:

```
[Test Folder]
days = 10000
tags = cat cute fluffy -dog -bat -fox
```

So I guess my issue is, how do I format my config.ini file so that I can get "every post in the past 10,000 days that has all the following tags: "cat", "cute", "fluffy", while excluding any posts that are tagged with "dog", "bat", and "fox"?

//

I'm running the latest version of Python 3 and I'm on OSX 10.13.6

**Comment by lurkbbs** [comment]
Well, I'm not sure if it's real tags or just some placeholder. If they are real, I just checked this on e621.net and there's no post at all that meets that tag combination at all.

If they are placeholders, please PM me on e621.net or on lurkbbs@gmail.com, just make sure they are actually present on the site itself.

Also, recently Cloudflare changed Recaptcha to hCaptcha. Since whole ip range of at least my city and most likely my country looks bad to Cloudflare, I'm unable to use e621dl until I figure out how to solve it. Wish me luck, and maybe by next week I could meaningfully help you if the tag combination actually have posts.

Also, looks like there is no `cute` tag, and that's just outdated example. Sorry.

**Comment by ChillAnon** [comment]
Those are placeholders. I'll email you the actual tags.

**Comment by lurkbbs** [comment]
God, such a simple reason, and I forgot it long ago: default rating is safe only.
And yes, I know that defaults in the template are misleading, I'll change it as soon as hCaptcha will be solved, not bypassed by a proxy.

Add this to an ini file and it all should work. Also, some posts may be unavailable for unregistered user, so you will need to create an account on e621 and get API key in "Account --> Manage API Access"

```
[Defaults]
min_score = -2147483647
min_favs = 0
ratings = s q e
max_downloads = inf

; uncomment and input real data if needed
; [Settings]
; login = <your e621.net login>
; api_key = <api key, made in account settings. *Not* your password>
```

EDIT: forgot about `[Settings]` section

**Comment by ChillAnon** [comment]
Okay,

So I edited the sections, this is what the bottom of my "config.ini" file looks like:

```
[Settings]
login = <login>
api_key = <api key>

[Test Folder]
tags = cats dogs birds -foxes -bats -snakes
```

And I still get the same results page, except this time it doesn't even scan the tags for posts anymore.

```
status: All complete
checked tag: all tags are valid
current config: config.ini
current section: None so far
recent warning: None so far
recent file downloaded: None so far
connection retries: None so far
posts so far: None so far
already exist: None so far
downloaded: None so far
copied: None so far
filtered: None so far
not found on e621: None so far
```

I've attached the config.ini file for reference (I took out the username and API key for privacy and security concerns)

[config.ini.zip](https://github.com/lurkbbs/e621dl/files/4446013/config.ini.zip)

**Comment by lurkbbs** [comment]
I answered in an email, but I'll answer here as well.

You need both `[Defaults]` and `[Settings]` sections, e.g.

```
[Settings]
login = <login>
api_key = <api key>

[Defaults]
min_score = -2147483647
min_favs = 0
ratings = s q e
max_downloads = inf

[Test Folder]
tags = cats dogs birds -foxes -bats -snakes
```

**Comment by ChillAnon** [comment]
That worked, thanks so much!!!
