### ISSUE TITLE
Missplaced Pools folders

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#29]
Mentioned in Issue #8 Download Pools? 
Pools folder gets added/coppied to all subfolders in a main search but not the main folder of said search

**AKA With my config like this**

[Defaults]
days = 365000000
ratings = q, e
min_score = 0
min_favs = 0
max_downloads = inf
subfolders = sub-catagory 1, sub-catagory 2
posts_from = api

[Blacklist]
tags = _"balcklisted Tags"_

;;;;; Sub-Catagories ;;;;;

[*sub-catagory 1]
Tags = sub-catagory 1
blacklist_default_subfolders = true

[*sub-catagory 2]
Tags = sub-catagory 2
blacklist_default_subfolders = true

;;;;; Prefilter ;;;;;

[<Prefilter>]
Tags = _"tags for prefiltering"_

;;;;; Main Searches ;;;;;

[Artist/Artist 1]
Tags = Artist 1
pool_post_strategy = move

[Artist/Artist 2]
Tags = Artist 2

[Artist/Artist 3]
Tags = Artist 3
pool_post_strategy = move
blacklist_default_subfolders = true

[Artist/Artist 4]
Tags = Artist 4
blacklist_default_subfolders = true

**I Get this**

Downloads
|
|--Artist 1 (main folder)
| |
| |-- .Images (subfolder)
| | |
| | | -- Pools (subfolder)
| | | |
| | | |-- _"Pool ID"_
| | | |
| | | |-- _"Pool ID"_
| | | |
| | | |-- etc.
| | |
| | | -- sub-catagory 1
| | |
| | | -- sub-catagory 2
| | |
| | |-- etc.
| |
| |-- .Animations (subfolder)
| | |
| | | -- Pools (subfolder)
| | | |
| | | |-- _"Pool ID"_
| | | |
| | | |-- _"Pool ID"_
| | | |
| | | |-- etc.
| | |
| | | -- sub-catagory 1
| | |
| | | -- sub-catagory 2
| | |
| | |-- etc.
|
|--Artist 2 (main folder)
| |
| |-- .Images (subfolder)
| | |
| | | -- sub-catagory 1
| | |
| | | -- sub-catagory 2
| | |
| | |-- etc.
| |
| |-- .Animations (subfolder)
| | |
| | | -- sub-catagory 1
| | |
| | | -- sub-catagory 2
| | |
| | |-- etc.
|
|--Artist 3 (main folder)
| |
| | -- Pools (subfolder)
| | |
| | |-- _"Pool ID"_
| | |
| | |-- _"Pool ID"_
| | |
| | |-- etc.
| |
| |-- All of Artist 3 posts
|
|--Artist 4 (main folder)
| |
| |-- All of Artist 4 posts

**When i should get this**

Downloads
|
|--Artist 1 (main folder)
| | 
| | -- Pools (subfolder)
| | |
| | |-- _"Pool ID"_
| | |
| | |-- _"Pool ID"_
| | |
| | |-- etc.
| |
| |-- .Images (subfolder)
| | |
| | | -- sub-catagory 1
| | |
| | | -- sub-catagory 2
| | |
| | |-- etc.
| |
| |-- .Animations (subfolder)
| | |
| | | -- sub-catagory 1
| | |
| | | -- sub-catagory 2
| | |
| | |-- etc.
|
|--Artist 2 (main folder)
| |
| |-- .Images (subfolder)
| | |
| | | -- sub-catagory
| | |
| | | -- sub-catagory
| | |
| | |-- etc.
| |
| |-- .Animations (subfolder)
| | |
| | | -- sub-catagory
| | |
| | | -- sub-catagory
| | |
| | |-- etc.
|
|--Artist 3 (main folder)
| | 
| | -- Pools (subfolder)
| | |
| | |-- _"Pool ID"_
| | |
| | |-- _"Pool ID"_
| | |
| | |-- etc.
| |
| |-- All of Artist 3 posts
|
|--Artist 4 (main folder)
| |
| |-- All of Artist 4 posts

**Comment by lurkbbs** [comment]
Sometimes next weekend, it should be possible to be done.

**Comment by lurkbbs** [comment]
See https://github.com/lurkbbs/e621dl/issues/31
