### ISSUE TITLE
Type tag doesn't seem to work

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#3]
I have had the program run for the day and I noticed that the program won't download any posts or create the folders for any search sections that use type:webm, type:gif, type:swf in the tags like in your example.
Here is on of my serch sections including the one for still images which works.
[Tags/Scalie/Images]
Tags = ~female ~intersex ~ambiguous_gender Scalie, -animated

[Tags/Scalie/Animated]
Tags = ~female ~intersex ~ambiguous_gender Scalie, type:swf

[Tags/Scalie/Gif]
Tags = ~female ~intersex ~ambiguous_gender Scalie, type:gif

[Tags/Scalie/Video]
Tags = ~female ~intersex ~ambiguous_gender Scalie, type:webm

I also tried it like 
[Tags/Scalie/Animated]
Tags = ~female ~intersex ~ambiguous_gender Scalie, 
type:swf

[Tags/Scalie/Gif]
Tags = ~female ~intersex ~ambiguous_gender Scalie, 
type:gif

[Tags/Scalie/Video]
Tags = ~female ~intersex ~ambiguous_gender Scalie, 
type:webm

and like this
[Tags/Scalie/Animated]
Tags = ~female ~intersex ~ambiguous_gender Scalie, 
type= swf

[Tags/Scalie/Gif]
Tags = ~female ~intersex ~ambiguous_gender Scalie, 
type= gif

[Tags/Scalie/Video]
Tags = ~female ~intersex ~ambiguous_gender Scalie, 
type= webm

both changes I made above didn't work and only downloading everything as if they where not there
like I mentioned in my other issue I dont know allot about programing but since there is not a tag for the type of post(gif,swf,webm,png,jpg) I dont think it would be viable to put the diffrent types in the tags line but do something like my third attempt with the type having its own line.
Edit: i dont know if this will help but this showed up druing the starting up process
[!] It is not possible to check if type:swf is valid.
[!] It is not possible to check if type:gif is valid.
[!] It is not possible to check if type:webm is valid.

**Comment by lurkbbs** [comment]
I'm sorry it took me so long to answer. I'll check it right now

**Comment by lurkbbs** [comment]
Just checked. There was a serious bug that made metatags useless. Fixed, binary is here:
https://github.com/lurkbbs/e621dl/releases/tag/v5.2.1

Edit: 
this works fine:

```
[Tags/Scalie/Images]
Tags = ~female ~intersex ~ambiguous_gender Scalie, -animated

[Tags/Scalie/Animated]
Tags = ~female ~intersex ~ambiguous_gender Scalie, type:swf

[Tags/Scalie/Gif]
Tags = ~female ~intersex ~ambiguous_gender Scalie, type:gif

[Tags/Scalie/Video]
Tags = ~female ~intersex ~ambiguous_gender Scalie, type:webm
```

But I suggest moving metatags closer to beginning of a tag field, like that:

```
[Tags/Scalie/Images]
Tags = ~female ~intersex ~ambiguous_gender Scalie, -animated

[Tags/Scalie/Animated]
Tags = type:swf ~female ~intersex ~ambiguous_gender Scalie

[Tags/Scalie/Gif]
Tags = type:gif ~female ~intersex ~ambiguous_gender Scalie

[Tags/Scalie/Video]
Tags = type:webm ~female ~intersex ~ambiguous_gender Scalie
```

Because only first 5 tags can be metatags, because only they a sent to e621 because there is tag limit on tag search.

Sorry it took me so long. This won't happen again.

**Comment by huskelord** [comment]
Its no problem thank you. I figured out that windows 10 lets you sort it themselves so I just went with a animated folder and a images folder and grouped the images in the animated folder by their type. Glad I cought the bug for you though.

**Comment by lurkbbs** [comment]
Glad it was not critical after all.
