### ISSUE TITLE
Blacklisting Images in Pools

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#31]
Ok so i noticed that I have some images that are in a pool in one place but out of a pool somewhere else
example being a image of a girl that is in a pool (not pool pool but image collection pool) and its get put into its pool folder when I get the artists images since i call for a pool and it doesnt show up anywhere else in that artists folder but it shows up in a folder calling for all images of girls

Basicly can you create a _blacklist_pooled_images = true_ line like the _blacklist_default_subfolders =_ line so i can keep pooled images out of areas I don't want pooled images or pools whatsoever

Edit: Please take care of misspalced pool folders first so I can impliment this easier when it is done if it is even possible

**Comment by lurkbbs** [comment]
Yeah, with `pool_post_strategy = move` all post that a in pools moved to pools.
With `pool_post_strategy = copy` they could be just copied, both in pools subfolders and in main folders.

There is no `pool_post_strategy = none`, but that's relevant only if you have `pool_post_strategy = ` in `defaults`.

Or do you want to not place an image at all in some folders if it's in a pool, something like `pool_post_strategy = forbid`?

**Comment by huskelord** [comment]
Yep that last part is exactly what I need.

**Comment by lurkbbs** [comment]
[e621dl.zip](https://github.com/lurkbbs/e621dl/files/4941955/e621dl.zip)

OK, I've added this:

`pool_post_strategy = none` to disable any pool interaction for a folder. May be useful if default `pool_post_strategy` is set.
`pool_post_strategy = forbid` prevents any images with at least one pool to download in a folder.

`pools_only_in_main = true` generates pools only in non '*' folder and not in any of subfolders.

Check out and close if this works for you. Before you ask, no, it's not possible for any `pools_...` settings to work with subfolders ☹️ 

That's all after summer.

**Comment by huskelord** [comment]
Ill get testing it out right a away but a couple of questions

1) what is do you mean by May be useful if default `pool_post_strategy` is set?

2) Does `pool_post_strategy = forbid` prevents any image that is in a pool form generating or just any images that was added to a pool folder in the config?

3) Does `pools_only_in_main = true` go in the `[Default]` , `[Settings]` or does it go into the searches themselves?

3) Is `pools_only_in_main = true` line necesarry for pools to go into the main folder or do they go there naturaly? 
            If it is not necesarry for the `pools_only_in_main = true` to be present for pools to go into the main folder, is it necesarry for pool folders to not go into the subfolders

4) With `pools_. . .`  codes not working in subfolders do you mean the '*' folders or serches that only have a `subolders  =` line?

**Comment by lurkbbs** [comment]
> what is do you mean by May be useful if default `pool_post_strategy` is set?

Like, you have lots of folders with pools, and one or two folders where you don't need neither pools subfolders nor forbid any posts from a pools, like if there is no `pool_post_strategy` at all. So you can add `pool_post_strategy=move` to defaults and `pool_post_strategy = none` to those two folders.

> Does `pool_post_strategy = forbid` prevents any image that is in a pool form generating or just any images that was added to a pool folder in the config?

For a folder, yes. Since there is no folder to place pools, there is no way to generate config for that. Of course, for any other folders with different setting all should work just fine

> Does `pools_only_in_main = true` go in the `[Default]` , `[Settings]` or does it go into the searches themselves?

`[Defaults]` and searches. After all, `[Defaults]` are just that, default values for searches, with exception for tags and `blacklist_default_subfolders`. 

> Is `pools_only_in_main = true` line necesarry for pools to go into the main folder or do they go there naturaly?
If it is not necesarry for the `pools_only_in_main = true` to be present for pools to go into the main folder, is it necesarry for pool folders to not go into the subfolders

It's necessary to be there (or in `[Defaults]`). It's kinda either they all go there, or just like before, some here, some there.

> With pools_. . . codes not working in subfolders do you mean the '*' folders or serches that only have a subolders = line

Well, better to show an example 

```ini
[*cat]
tag = cat
pool_post_strategy = move ; This line won't do anything

[cat dog]
tag = ~cat ~dog
subfolders=cat
pool_post_strategy = move ; This line will work for this folder and all of its subfolders

[bat]
tag = bat
pool_post_strategy = move ; This line will work for this folder

[*dog]
tag = dog

[cat dog 2]
subfolders = cat dog
pool_post_strategy = move ; This line should work for this folder and all of its subfolders. 
                          ; But I honestly don't know if it will, forgot to test that option

[*cat_dog_3]
subfolders = cat dog
pool_post_strategy = move ; This line won't do anything

[bat 2]
tag = bat
subfolders = cat_dog_3
pool_post_strategy = move ; This line will work for this folder and all of its subfolders
```

**Comment by huskelord** [comment]
got it thanks will let you know when the program finishes its run and close the issues that can be closed

**Comment by huskelord** [comment]
Sorry for the late reply had some problems I had to take care of It all works great

`cat dog 2]
subfolders = cat dog
pool_post_strategy = move ; This line should work for this folder and all of its subfolders. 
                          ; But I honestly don't know if it will, forgot to test that option`

This works though i only used `pool_post_strategy = forbid`

Only issurs I can think of left is the missorded pools and Pool_.... lines not working in '*' searches
