### ISSUE TITLE
Posts won't download

### ISSUE THREAD

**Issue by necrorika** [lurkbbs/e621dl#33]
It appears that you are unable to download posts that you would otherwise have to log in to view. I don't know if there is a way around this, I could not find one.

**Comment by lurkbbs** [comment]
There is. In settings, add 

```ini
[Settings]
...
login = your e621 login
api_key = your e621 api key generated in account settings
```

To get your api key, go https://e621.net/users/home and then to "Manage API Access"

**Comment by lurkbbs** [comment]
Oh, while you're here, where did you search? Wherever you are, I should add relevant info there.
