### ISSUE TITLE
Questions about Prune_ and Offline Sections of [Settings] 

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#35]
I have a couple of qestions that I have been confused about that forgot to ask before or was forgotten in a random issue

1) How do the prune_downlaods and prune_cache work in genral and most importanlty with mulitple configs (I think i undersood what was said in the ReadMe.md but id like clarification just to be sure)

2) Is running the progam offline the only way to run a config wihtout it donwloading new files/posts

 (will have follow up qestions after i get a responce)

**Comment by lurkbbs** [comment]
> How do the prune_downlaods and prune_cache work in genral and most importanlty with mulitple configs (I think i undersood what was said in the ReadMe.md but id like clarification just to be sure)

In general, they should, let me check ...

Shit! There is a bug right now, only last config actually matters. They should be false unless true in at least one of configs. Weekend. All in the weekend, Sunday to be specific. Also, whatever there is in pools.ini is ignored.
But for now, `prune_downloads`, `prune_cache`, `no_redownload`, and `pool_download_generate` are used from the last config.

> Is running the progam offline the only way to run a config wihtout it donwloading new files/posts.

Yes, hence the term. But that is per config basis. Waaaait, let me check.
...
...
Ugh. OK, you _can_ safely use it on a per config basis. A long time ago it was not possible, but it should be now.


The more question you get, the more correct this app and docs would be, so bring it on!

**Comment by huskelord** [comment]
for my first question i guess this should end up fixed thus ill leave it be

for my second qestion would making the `posts_from =` the deciding factor if new posts get donwloaded or not. 
Or would making a new line be better

Reason Im suggesting that is becaues it sounds like the `offline` line is being wierd and fixing it might remove said functionality

**Comment by lurkbbs** [comment]
> Reason Im suggesting that is becaues it sounds like the offline line is being wierd and fixing it might remove said functionality

`posts_from` will never prevent downloads, only replacing long iteration over posts from 320 posts/s to a bit/lot faster, depending on size of a config. Best used with a single prefilter. Now that I think about it, since metatags are not supported with getting from db anyway, I should make a default prefilter for offline use.

`offline` _should_ work fine with per config settings. If it's not, it's a bug and most definitely not a feature, _unlike_ what's written in the docs.

**Comment by huskelord** [comment]
Got it. If it stops working I'll let you know.
