### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#37]
I can't figure out why but there is an artist who I am not getting all of their images donwloaded for some reason and I can't see any reason for them not to be downloaded the artist is shait by the way

**Comment by lurkbbs** [comment]
There are not a lot of it anyway. Make sure there is no some blacklisted tag or condition. I'll look into it this Sunday. Probably. There a lot of work already, so I'm not sure I'll do everything in time.

**Comment by lurkbbs** [comment]
OK, closing, not enough tags for a half of images.

**Comment by huskelord** [comment]
Wait so the reason was there wasn't enough tags ?

**Comment by lurkbbs** [comment]
Yeah. Tag them and they should be there in the folder.
