### ISSUE TITLE
UTF-8 encoding make the downloader crash

### ISSUE THREAD

**Issue by bugmaschine** [lurkbbs/e621dl#39]
When the config file is utf-8 encoded it crashes the downloader 

The workaround is to convert the utf-8 encoded config file to iso-8859-1

`iconv --from-code=UTF-8 --to-code=ISO-8859-1 config.ini > config.ini`

**Comment by lurkbbs** [comment]
O_O I kinda didn't expect that it opens with that. If you have utf-8 tags like _pokémon_ try utf-8 with BOM.
Here's the relevant part:

```python
with open(filename, 'rt', encoding = 'utf_8_sig') as infile:
        config.read_file(infile)
```
