### ISSUE TITLE
Program closes exactly when a Error occurs and can't see what the problem is.

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#4]
I noticed that when there is a bug that the program will put a error script but will immediately close after the script comes up. 
I was wondering if there was a way for the program to know not to close when there is a error but put up a press enter to close message and not close or something similar.
Also could you put up a press enter to close when the program has finished.

**Comment by lurkbbs** [comment]
With shortcuts made in multithreaded code, it's not that simple. I'll do it someday, but until that time you can run e621dl from command line. Just right click on empty space in a folder with e621dl, select "PowerShell" or "Command Line" and type `./e621dl.exe` there. This way app won't close window.

Alternatively, place bat file from zip below in a folder with e621dl.exe and run from it. It should give you
"press any key to continue" when script ends with or without errors
[e621_noclose.zip](https://github.com/lurkbbs/e621dl/files/2898347/e621_noclose.zip)

**Comment by lurkbbs** [comment]
Also, there is new bug in this update?
If there is, can you copy your config.ini here or send me to lurkbbs@gmail.com ?

**Comment by huskelord** [comment]
No there was not a new bug its was just me having a typo in the folder names causing the game to crash. I had to record the program and stop the video at the time it closed to figure out what was wrong because the error text explained it but I couldent see it.

**Comment by lurkbbs** [comment]
OK. So, e621_noclose.bat is good enough?

**Comment by huskelord** [comment]
Yep. I don’t have any problems at all.
