### ISSUE TITLE
sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by jahkyah** [lurkbbs/e621dl#40]
Hi!

Hope you are doing well!

I am getting this error when (to what I believe) halfway through my config.ini file it throws this exception.

I do not think it is an issue with the config.ini file as it successfully verifies it and starts downloading.

Only when it gets half-way done downloading from the config.ini file it throws this exception.

![image](https://user-images.githubusercontent.com/53247317/90795739-6d244f00-e2dc-11ea-93dc-a90d91f69c03.png)

Exception during download:
Traceback (most recent call last):
  File ".\e621dl.py", line 771, in process_config
    pathes_storage.add_pathes(directories, filename)
  File "H:\e621dl_lib\local.py", line 338, in add_pathes
    self.cur.execute('INSERT OR REPLACE INTO new_files VALUES (?);', (filepath,))
sqlite3.DatabaseError: database disk image is malformed
PS H:\>

When I run the program again it throws a blank exception so I cannot tell exactly what exception it is throwing.

![image](https://user-images.githubusercontent.com/53247317/90796299-1f5c1680-e2dd-11ea-9b96-303e84893744.png)

If I had to guess it could be the same exception being thrown as above.

I am going to try to run this script on a separate HDD to see if this issue still persists as I am not sure if it would an issue with my hardware, script or on E621's side of things.

Below is the same exception but on another HDD

![image](https://user-images.githubusercontent.com/53247317/90798053-6ba85600-e2df-11ea-919a-3a24113e1a51.png)

Exception during download:
Traceback (most recent call last):
  File ".\e621dl.py", line 771, in process_config
    pathes_storage.add_pathes(directories, filename)
  File "F:\e621dl_lib\local.py", line 338, in add_pathes
    self.cur.execute('INSERT OR REPLACE INTO new_files VALUES (?);', (filepath,))
sqlite3.DatabaseError: database disk image is malformed
PS F:\>

Will you be needing my config.ini file?

Thanks!

**Comment by lurkbbs** [comment]
I'm not sure how this happened, but it looks like database that stores pathes of files that was ever downloaded is broken. Try remove `files.db`. If you want to save as much as possible, _maybe_ this could help:

* Get [Db browser for SQLite](https://sqlitebrowser.org/dl/)
* Open `files.db` then execute `PRAGMA  integrity_check;` and/or dumping-restoring it using [this instructions](https://www.sysinfotools.com/blog/fix-error-sqlite-database-disk-image-malformed/). 

Hope this helps

**Comment by jahkyah** [comment]
Thanks for the tip!

I will go ahead and delete the files.db file and have the script rebuild it!

I will let you know if this solves the issue!

**Comment by jahkyah** [comment]
Hi!

I believe deleting the files.db file fixed this issue. I was able to get past the part where it would throw that exception!

I will close this issue and will reopen if it occurs again!
