### ISSUE TITLE
Unable to get past CAPTCHA using given useragent

### ISSUE THREAD

**Issue by jahkyah** [lurkbbs/e621dl#43]
Hello!

Hope all is well. When I have started up the script, I was given the instructions on how to get past the cloudflare by setting cookies on my browser (google chrome)

https://github.com/lurkbbs/e621dl/blob/master/Cloudflare.md

I had read the instructions it said to use : 

current userAgent of e621dl 

BUT The output from the script about cloudflare uses this userAgent:  

e621dl (lurkbbs) -- Version 5.11.1

I have tried both useragents with no success getting past cloudflare.

For example, when I solve the CAPTCHA using one or the other of the userAgents I am unable to get past the point where I solved the CAPTCHAS. Occasionally it would refresh and make me solve the CAPTCHA twice.  At first it looked like it was doing something.

![image](https://user-images.githubusercontent.com/53247317/119583301-4aa3f280-bd94-11eb-8dfe-344195e58941.png)

At this point cloudflare appears to be going no where. I have waited approximately 20mins to see if it just taking its time.

I know it is not something the dev may support but I am curious if anyone else is having this issue?

Let me know if you need more information!

EDIT: 

May be helpful to post the screenshot of both userAgents

One from script:
![image](https://user-images.githubusercontent.com/53247317/119583783-4fb57180-bd95-11eb-878e-fd265e43b2ff.png)

One from instructions:
![image](https://user-images.githubusercontent.com/53247317/119584430-83dd6200-bd96-11eb-98ba-ba935aae79e6.png)

Once you solve a captcha it seems to hang on cloudflare.

**Comment by TechnichalDoge** [comment]
I am having the same issue. tried it multiple times.

**Comment by TechnichalDoge** [comment]
after i run the program it also deletes the cookie .txt file's contents

**Comment by TechnichalDoge** [comment]
Something that might help to note is that other bots have this issue as well, apparently e6 turned on their cloudflare ddos protection. the furexplicitbot on discord mentioned this.

**Comment by TechnichalDoge** [comment]
E6 either removed it or is having troubles with its ddos protection now; so the e621dl is working for the time being; but for how long, dunno.

**Comment by jahkyah** [comment]
Yeah, I am not sure if I need to keep this issue open as this is not something lurkbbs could potentially fixed. I will keep it up for  a few more days!

Everything is working fine right now!

**Comment by TechnichalDoge** [comment]
There is a request limit apparently now; after a while it errors out and when i go into e621 itself it asks me to click a button to confirm i am not a robot; after i do such it'll allow me to restart e621dl. There might be some bodge to get around this in the back end.

**Comment by TechnichalDoge** [comment]
> There is a request limit apparently now; after a while it errors out and when i go into e621 itself it asks me to click a button to confirm i am not a robot; after i do such it'll allow me to restart e621dl. There might be some bodge to get around this in the back end.

Perhaps having e621dl pause when it hits this manual button and have the user clear it. I'll go see if i can make a pr for that later.
