### ISSUE TITLE
401 Client Error when using pool_download_generate = true

### ISSUE THREAD

**Issue by minimal-effort** [lurkbbs/e621dl#44]
When attempting to download pools the api returns 401 when pre-filtration begins
is the pool downloader not using the supplied api key?

      Exception in api iterator:
      Traceback (most recent call last):
        File "/path_to/e621dl/./e621dl.py", line 198, in prefilter_build_index
          for results in gen(last_id, **kwargs):
        File "/path_to/e621dl/e621dl_lib/remote.py", line 265, in get_posts
          response.raise_for_status()
        File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
          raise HTTPError(http_error_msg, response=self)
      requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://e621.net/posts.json
      Http Status:  401
      Text:  {
        "success": false,
        "message": "SessionLoader::AuthenticationFailure",
        "code": null
      }

**Comment by jahkyah** [comment]
Are you using the API key that you created on your e621 account? It will require your login (username) and API key.

**Comment by minimal-effort** [comment]
yes, and I am using both.

**Comment by minimal-effort** [comment]
> is the pool downloader not using the supplied api key? ~me probably

After some light debugging I now know it is, however, the loop on line 198 doesn't fail immediately; Instead it loops on lines 198 and 186 several times before failing and even runs the try -> except block a few times.

**Comment by minimal-effort** [comment]
it seems that the first prefilter uses the config.ini key while all subsequent requests use the pools.ini key which had not been updated.
