### ISSUE TITLE
I'm getting an HTTP error

### ISSUE THREAD

**Issue by BurningCayenne** [lurkbbs/e621dl#6]
I run e621dl.exe and it validates all the tags, and then it says
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e621.net/post/show.json`
and closes.

**Comment by lurkbbs** [comment]
This may be troubles on e621dl. Just checked, e621dl downloads just fine. Please check again.

**Comment by lurkbbs** [comment]
Totally unrelated, found a bug in new version, using cache or, more likely, duplicate function is impossible if no custom format specified. Fixing right now

**Comment by lurkbbs** [comment]
And fixed
https://github.com/lurkbbs/e621dl/releases/tag/v5.4.1

**Comment by lurkbbs** [comment]
Please tell if everything works or not

**Comment by lurkbbs** [comment]
Found (and fixed) one bug today, if there was some partially downloaded file with custom name format, program crashed trying to to download it. Again, please tell me if your bug is still exists.

**Comment by BurningCayenne** [comment]
Yeah, it works. Thanks!

**Comment by lurkbbs** [comment]
You're welcome!
