### ISSUE TITLE
Post Blacklist

### ISSUE THREAD

**Issue by huskelord** [lurkbbs/e621dl#9]
I was wondering if it would be possible to make a blacklist but only for spacific posts
I want to save space and dont want to have everysingle update post of a flash game/animation is there a way to block that post so it wont redonwload every time i run the program

if there is a way to do this already how would i go about doing that.

**Comment by lurkbbs** [comment]
Nope, not for now. For one or two post, you can add something like `-id:100` for both prefilters as first tags. For more than five and not in prefilters you're out of luck until at least December.

**Comment by lurkbbs** [comment]
I suppose this is more pressing than pool downloads.

How do you see it? I came up with these options:

* blocked.txt where each line contains blocked id. Fast, simple, a bit hard to maintain.
* special recycle folder. Just place all files you want to blacklist, and on next start e621 will delete them (from all folders and from cache) and will add them to blocked.txt. Simpler, but files won't be removed until e621dl restart.
* Same, but for all folders. Before exit, state of downloads and cache folder will be saved. If some files be deleted, all files with the same id will be deleted as well and added to blocklist.txt

So, what do you think?

**Comment by huskelord** [comment]
second on sounds best and least likely to cause any problems down the line.
Edit1: also can the blocked.txt where each line contains blocked id be sorted by name and not in the order of deletion which i fear my happen

**Comment by lurkbbs** [comment]
Yeah, it can, but why? Ctrl + F to find works better than manual search, sorted list or not.

**Comment by huskelord** [comment]
... I wish i new that was a thing so long ago.

**Comment by huskelord** [comment]
I dont trust myself to remember so I'll just add this here 
Auto-delete posts from folders that they are no longer relevant to (and cache/db if they are not relevent to anyting of that is possible)

**Comment by lurkbbs** [comment]
Deletion of irrelevant posts is added, post blacklist as well
https://github.com/lurkbbs/e621dl/releases/tag/v5.7.0

**Comment by huskelord** [comment]
Thank you for your help

**Comment by lurkbbs** [comment]
You're welcome!
